version: "3"
services:
  reverse-proxy:
    image: traefik:v1.7
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - ./acme.json:/acme.json

  backend:
    container_name: backend
    image: latest123/backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo

  frontend:
    container_name: frontend
    image: latest123/frontend
    restart: always
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "433:433"

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
