logLevel = "DEBUG"
defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "bouttondor.com"
watch = true
exposedbydefault = false
swarmmode = true

[acme]
email = "vivien.noel@live.fr"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
[acme.tlsChallenge]

[[acme.domains]]
  main="troisfils.com"
  sans=["www.bouttondor.com", "api.bouttondor.com", "traefik.bouttondor.com"]